### ISSUE TITLE
If a date format is entered, the database value will not be shown in the field

### ISSUE THREAD

**Issue by agruenberg** [melohagan/budibase-component-kasper-date-picker#3]
I added the date-picker to a update form and changed the date format to dd.MM.yyyy.  Afterwards I launched this form and the value, that should be shown there, is not appearing (see attached Video). The settings are the same as for the build-in date-picker (see attached screenshot).
![Bildschirmfoto von 2022-10-19 16-42-51](https://user-images.githubusercontent.com/19472717/196723589-f4a18273-371f-48d7-a1e9-9f14e9101e4c.png)

[vokoscreen-2022-10-19_16-25-10.webm](https://user-images.githubusercontent.com/19472717/196723303-9d9f6c22-9072-4a0e-ad6e-f3b7426ad012.webm)

**Comment by melohagan** [comment]
Hey @agruenberg 

Would be be able to show me your **Save Row** action?

**Comment by agruenberg** [comment]
Sure
![Bildschirmfoto von 2022-10-19 16-47-18](https://user-images.githubusercontent.com/19472717/196724819-b2ef956e-1b7d-490b-9abd-4e29a1d63841.png)

**Comment by melohagan** [comment]
And the form schema is set to `invoices` and the form field for the date-picker is set to `Date of Invoice` with the correct capitalisation of your table column?

**Comment by agruenberg** [comment]
Yes, as defined in the screenshot. It is the same definition as before, only the component has changed. Before I used the build in picker. The selected value is also transferred to the database as you can see in the video (with -1 day, but this is an extra issue).  Only the loading and showing within the component seems not to work.

**Comment by melohagan** [comment]
Perfect, and finally what is your timezone? Just in case that would cause issue.

**Comment by agruenberg** [comment]
Austria, Vienna GMT+2 ;)

**Comment by melohagan** [comment]
Hey @agruenberg 

I've added an option to ignore timezone. I think what may have been happening here is that when you saved the row to the database, the value was being set as `... 12 23:00:00` instead of `... 13 00:00:00`

So upgrade and make sure this setting is ticked:
![Screenshot 2022-10-21 at 16 14 13](https://user-images.githubusercontent.com/101575380/197229791-5c7031a2-b264-40e0-b0e2-2803623ad476.png)

Let me know if that fixes it for you! I'll re-open the issue if the problem still persists.
